<?php
require_once __DIR__ . '/../../functions.php';

start_session();
page_header('QR Code Generator');
?>
<div class="container" style="max-width: 800px;">
    <h1 class="h4 mb-1 reveal in-view">🔲 QR Code Generator</h1>
    <p class="text-secondary mb-4 reveal in-view">Create a scannable QR code for any text, URL or Wi-Fi setup string. Sizes, margins and colors are fully configurable.</p>

    <div class="card reveal">
        <div class="card-body">
            <div class="mb-3">
                <label class="form-label">Data (text / URL / whatever)</label>
                <input id="qr-data" class="form-control" style="font-size:.95rem;" value="https://kevbin.ct.ws/" oninput="makeQr()">
            </div>
            <div class="row g-3 mb-3">
                <div class="col-md-3">
                    <label class="form-label">Size (px)</label>
                    <input id="qr-size" class="form-control" type="number" min="100" max="1000" step="50" value="300" oninput="makeQr()">
                </div>
                <div class="col-md-3">
                    <label class="form-label">Margin</label>
                    <input id="qr-margin" class="form-control" type="number" min="0" max="10" value="1" oninput="makeQr()">
                </div>
                <div class="col-md-3">
                    <label class="form-label">Dark color</label>
                    <input id="qr-dark" class="form-control" type="color" value="#000000" oninput="makeQr()">
                </div>
                <div class="col-md-3">
                    <label class="form-label">Light color</label>
                    <input id="qr-light" class="form-control" type="color" value="#ffffff" oninput="makeQr()">
                </div>
            </div>
            <div class="text-center p-3" style="background:#0b0b0b;border:1px solid var(--line);border-radius:12px;">
                <div id="qr-box" class="d-inline-block">
                    <img id="qr-img" alt="QR code" style="image-rendering:pixelated;border-radius:8px;">
                </div>
                <div id="qr-err" class="text-danger small mt-2"></div>
                <div class="mt-3">
                    <a id="qr-dl" class="btn btn-primary btn-sm" download="qr-code.png">⬇ Download PNG</a>
                </div>
            </div>
            <p class="text-secondary small mt-3 mb-0">QR images are generated by an external public API
            (goqr.me). Do not put secrets inside QR codes made here.</p>
        </div>
    </div>
</div>
<script>
function makeQr() {
    var data = $('qr-data').value.trim();
    var err = $('qr-err');
    if (!data) { $('qr-img').style.display = 'none'; err.textContent = 'Enter some data first.'; return; }
    var size = Math.max(100, parseInt($('qr-size').value, 10) || 300);
    var margin = Math.max(0, parseInt($('qr-margin').value, 10) || 1);
    var dark = $('qr-dark').value.replace('#', '');
    var light = $('qr-light').value.replace('#', '');
    var url = 'https://api.qrserver.com/v1/create-qr-code/?size=' + size + 'x' + size +
        '&margin=' + margin + '&color=' + encodeURIComponent(dark) + '&bgcolor=' + encodeURIComponent(light) +
        '&data=' + encodeURIComponent(data);
    $('qr-img').src = url;
    $('qr-img').style.display = 'inline-block';
    $('qr-img').width = Math.min(size, 400);
    $('qr-dl').href = url;
    err.textContent = '';
}
makeQr();
function $(id) { return document.getElementById(id); }
</script>
<?php page_footer(); ?>